version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: magento-mysql
        working_dir: /application
        volumes:
            - .:/application
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=magento
            - MYSQL_USER=user
            - MYSQL_PASSWORD=magento
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        container_name: magento-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: magento-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
