version: "3.1"
services:
    smtp:
        image: namshi/smtp
        container_name: magento-smtp
        restart: always
        ports:
        - "25:25"
        environment:
        #  # MUST start with : e.g RELAY_NETWORKS: :192.168.0.0/24:10.0.0.0/16
        #  # if acting as a relay this or RELAY_DOMAINS must be filled out or incoming mail will be rejected
           RELAY_NETWORKS: :192.168.0.0/24
        #  # what domains should be accepted to forward to lower distance MX server.
        #  RELAY_DOMAINS: <domain1> : <domain2> : <domain3>
        #  # To act as a Gmail relay
        #  GMAIL_USER:
        #  GMAIL_PASSWORD:
        #  # For use with Amazon SES relay
        #  SES_USER:
        #  SES_PASSWORD:
        #  SES_REGION:
        #  # if provided will enable TLS support
        #  KEY_PATH:
        #  CERTIFICATE_PATH:
        #  # the outgoing mail hostname
        #  MAILNAME:
        #  # set this to any value to disable ipv6
        #  DISABLE_IPV6:
        # # Generic SMTP Relay
        # SMARTHOST_ADDRESS:
        # SMARTHOST_PORT:
        # SMARTHOST_USER:
        # SMARTHOST_PASSWORD:
        # SMARTHOST_ALIASES:
    mysql:
        image: mysql:5.7
        container_name: magento-mysql
        working_dir: /application
        volumes:
            - .:/application
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=magento
            - MYSQL_USER=user
            - MYSQL_PASSWORD=magento
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        container_name: magento-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: magento-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
